export const valueVoiceMotion = {
  firstHandoffViewportStart: 0.3,
  laterHandoffViewportStart: 0.56,
  firstHandoffDistance: 0.42,
  laterHandoffDistance: 0.4,
  reducedMotionThreshold: 0.52,
  morphBlur: 9.5,
  morphBlurRamp: 0.64,
  identityPinTopVh: 78,
  identityPinTopVhNarrow: 82,
  valuesStickTopVh: 36,
  identityPinRelease: 0.12,
  aspectRevealMargin: '0px 0px -14% 0px',
  aspectRevealThreshold: 0.16,
} as const;
