export const personalNoteMotion = {
  viewportStart: 0.72,
  viewportEnd: 0.02,
  headingStart: 0.18,
  headingDistance: 0.2,
  headingVisibilityStart: 0.45,
  headingVisibilityDistance: 0.4,
  boxVisualTop: 0.33,
  headingRestGapPx: 48,
  headingClearanceFadePx: 28,
  notesRiseStart: 0.34,
  notesRiseDistance: 0.2,
  notesSpreadStart: 0.5,
  notesSpreadDistance: 0.32,
  noteOpacityStart: 0.55,
  noteOpacityDistance: 0.2,
  noteOpacityStagger: 0.04,
  sourceScale: 0.96,
  clusterScale: 0.985,
  clusterGapPx: 4,
  portraitReflowDurationMs: 280,
  reducedInteractionDurationMs: 120,
  doodleBoundaryInsetPx: 24,
  doodleBoundaryResistance: 0.42,
  doodleReleaseDurationMs: 280,
} as const;
